### PR TITLE
add -coverpkg support

### LINKED ISSUE #8: flag provided but not defined: -coverpkg
I'm trying to run `gotestcover -v -coverprofile cover.out -coverpkg $(shell go list ./... | grep -v vendor/ | paste -s -d, -) $(shell go list ./... | grep -v vendor/)`.

Also, it would be nice if `gotestcover` was able to:
1) omit `vendor/`;
2) optionally populate the value of `-coverpkg` automatically.

### PR DESCRIPTION
**Pull request by powerman**
This isn't portable (*NIX only), but it does it work. I just don't have time right now to rewrite it in pure Go.

Looks like this works correctly both when -coverpkg set to ./... or selected packages.

close #8

### CODE REVIEW

**Comment by pierrre** [comment]
Does it work with `count` or `atomic` "covermode"?

**Comment by powerman** [comment]
Sure. It doesn't _add_ numbers, of course, just take the largest one - so results may not be precise but should be good enough.

**Comment by powerman** [comment]
Update PR with implementation in pure Go and adding numbers to get precise results. :smiling_imp:

**Comment by pierrre** [comment]
Please read https://github.com/pierrre/gotestcover#deprecated

sorry

**Pull request closed without merging**
